In [9]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [13]:
#[Problem 1] Matrix product is calculated manually
# the element of result matrix should be equal to multiplication of column of the first matrix and row of the second matrix 
c_array = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))

for i in range(a_ndarray.shape[0]):
    for j in range(b_ndarray.shape[1]):
        c_array[i, j] = np.sum(a_ndarray[i, :] * b_ndarray[:, j])
    
c_array

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

In [13]:
#[Problem 1] Matrix product is calculated manually
c_array = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))

for i in range(a_ndarray.shape[0]):
    for j in range(b_ndarray.shape[1]):
        c_array[i, j] = np.sum(a_ndarray[i, :] * b_ndarray[:, j])
    
c_array

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

In [11]:
#[Problem 2] Calculation by NumPy function
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

result = np.matmul(a_ndarray, b_ndarray)
print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [14]:
#[Problem 3] Implementation of calculation of a certain element
def calculate_element(a, b, i, j):
    element = 0
    for k in range(len(a[0])):
        element += a[i, k] * b[k, j]
    return element

element_00 = calculate_element(a_ndarray, b_ndarray, 0, 0)
print(element_00)

6


In [20]:
#[Problem 4] Creating a function that performs matrix multiplication

def matrix_multiply(a, b):
    c = np.zeros((len(a), len(b[0])))
    for i in range(len(a)):
        for j in range(len(b[0])):
            c[i, j] = calculate_element(a, b, i, j)
    return c

result_scratch = matrix_multiply(a_ndarray, b_ndarray)
print(result_scratch)


def matrix_multiply_safe(a, b):
    if a.shape[1] != b.shape[0]:
        print("Error: Matrix multiplication is not defined for the given matrices.")
        return None
    else:
        return matrix_multiply(a, b)

# Example usage:
d_ndarray = np.random.rand((5, 4))
e_ndarray = np.random.randint((6, 7))
result_safe = matrix_multiply_safe(d_ndarray, e_ndarray)
if result_safe is not None:
    print(result_safe)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
(2,)


IndexError: tuple index out of range

In [8]:
# Problem 6: Labeling
labels = np.zeros((1000, 1))
labels[500:] = 1
    
combined_data = np.hstack((data, labels))
print(combined_data.shape)
combined_data

(1000, 3)


array([[-4.80006782, -1.54698618,  0.        ],
       [-4.63714503, -0.21987973,  0.        ],
       [-4.46267867, -2.08076347,  0.        ],
       ...,
       [-0.2185878 , -3.15676476,  1.        ],
       [-1.37970304, -4.27950068,  1.        ],
       [ 1.49786804, -2.33126243,  1.        ]])